apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcheck
  labels:
    app: productcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcheck
  template:
    metadata:
      labels:
        app: productcheck
    spec:
      containers:
        - name: productcheck
          image: username/productcheck:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          #readinessProbe:
            #httpGet:
              #path: '/'
              #port: 8080
            #initialDelaySeconds: 10
            #timeoutSeconds: 2
            #periodSeconds: 5
            #failureThreshold: 10
          #livenessProbe:
            #httpGet:
              #path: '/'
              #port: 8080
            #initialDelaySeconds: 120
            #timeoutSeconds: 2
            #periodSeconds: 5
            #failureThreshold: 5